export interface PatientData {
  drgCode: number;
  description: string;
  code: string;
  amount: number;
  patientId: string;
  patientName: string;
  status: string;
}

// Correctly typed variable


// {
//       drgCode: 123,
//       description: 'Urinary System Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1900992.33,
//       patientId: 'G2EF3E',
//       patientName: 'Noah Williams',
//       status: 'Finished',
//     },
//     {
//       drgCode: 124,
//       description: 'Respiratory Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1000992.33,
//       patientId: 'D2EF3E',
//       patientName: 'Jessica Lee',
//       status: 'Unassigned',
//     },
//     {
//       drgCode: 125,
//       description: 'Respiratory Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1000992.33,
//       patientId: 'D2EF3E',
//       patientName: 'Jessica Lee',
//       status: 'Unassigned',
//     },
//     {
//       drgCode: 126,
//       description: 'Respiratory Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1000992.33,
//       patientId: 'D2EF3E',
//       patientName: 'Jessica Lee',
//       status: 'Unassigned',
//     },
//     {
//       drgCode: 127,
//       description: 'Respiratory Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1000992.33,
//       patientId: 'D2EF3E',
//       patientName: 'Jessica Lee',
//       status: 'Unassigned',
//     },
//     {
//       drgCode: 128,
//       description: 'Urinary System Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1900992.33,
//       patientId: 'G2EF3E',
//       patientName: 'Noah Williams',
//       status: 'Finished',
//     },
//     {
//       drgCode: 129,
//       description: 'Respiratory Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1000992.33,
//       patientId: 'D2EF3E',
//       patientName: 'Jessica Lee',
//       status: 'Unassigned',
//     },
//     {
//       drgCode: 130,
//       description: 'Respiratory Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1000992.33,
//       patientId: 'D2EF3E',
//       patientName: 'Jessica Lee',
//       status: 'Unassigned',
//     },
//     {
//       drgCode: 131,
//       description: 'Respiratory Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1000992.33,
//       patientId: 'D2EF3E',
//       patientName: 'Jessica Lee',
//       status: 'Unassigned',
//     },
//     {
//       drgCode: 132,
//       description: 'Respiratory Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1000992.33,
//       patientId: 'D2EF3E',
//       patientName: 'Jessica Lee',
//       status: 'Unassigned',
//     },
//     // add more records as needed
//     {
//       drgCode: 133,
//       description: 'Urinary System Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1900992.33,
//       patientId: 'G2EF3E',
//       patientName: 'Noah Williams',
//       status: 'Finished',
//     },
//     {
//       drgCode: 134,
//       description: 'Respiratory Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1000992.33,
//       patientId: 'D2EF3E',
//       patientName: 'Jessica Lee',
//       status: 'Unassigned',
//     },
//     {
//       drgCode: 135,
//       description: 'Respiratory Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1000992.33,
//       patientId: 'D2EF3E',
//       patientName: 'Jessica Lee',
//       status: 'Unassigned',
//     },
//     {
//       drgCode: 136,
//       description: 'Respiratory Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1000992.33,
//       patientId: 'D2EF3E',
//       patientName: 'Jessica Lee',
//       status: 'Unassigned',
//     },
//     {
//       drgCode: 137,
//       description: 'Respiratory Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1000992.33,
//       patientId: 'D2EF3E',
//       patientName: 'Jessica Lee',
//       status: 'Unassigned',
//     },
//     {
//       drgCode: 138,
//       description: 'Urinary System Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1900992.33,
//       patientId: 'G2EF3E',
//       patientName: 'Noah Williams',
//       status: 'Finished',
//     },
//     {
//       drgCode: 139,
//       description: 'Respiratory Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1000992.33,
//       patientId: 'D2EF3E',
//       patientName: 'Jessica Lee',
//       status: 'Unassigned',
//     },
//     {
//       drgCode: 140,
//       description: 'Respiratory Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1000992.33,
//       patientId: 'D2EF3E',
//       patientName: 'Jessica Lee',
//       status: 'Unassigned',
//     },
//     {
//       drgCode: 141,
//       description: 'Respiratory Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1000992.33,
//       patientId: 'D2EF3E',
//       patientName: 'Jessica Lee',
//       status: 'Unassigned',
//     },
//     {
//       drgCode: 142,
//       description: 'Respiratory Infection and Inflammation with MCC',
//       code: 'ABCDE1245',
//       amount: 1000992.33,
//       patientId: 'D2EF3E',
//       patientName: 'Jessica Lee',
//       status: 'Unassigned',
//     },
//     // add more records as needed